# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f29df7fff2f9457d26e8b3fb4a6e9abc40f9dc238de267436633ec99f32344ebe337a60703a3f356bd524691fa3b6692c7b27d087b75c8cb3a7d8bf7553520ea

test:
  secret_key_base: 3e133a479db396c2e81590760885008be1c6ec9fa4785ef0549204e13f290b9d596ba66423b3008c71a118eee340b42a303d3c8f56aa4d86a8ad95f31ad26ada

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
